server:
  port: 7901
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
spring:
  application:
    name: provider-demo